[package]
name = "vertice-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
jsonc-parser = { version = "0.33", default-features = false }
serde = { workspace = true }
serde_norway = "0.9"
thiserror = { workspace = true }
ts-rs = { workspace = true }
unicode-normalization = { workspace = true }
walkdir = "2"

[dev-dependencies]
serde_json = "1"

[lints]
workspace = true
