// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed set of clients the PoC scans. Deliberately minimal: only the
 * clients the PoC ships adapters for (Claude Code, OpenCode). Growing this
 * set is expected as later adapter phases land, but it stays a closed
 * enum, never `#[non_exhaustive]`.
 */
export type ClientKind = "claudeCode" | "openCode";
