// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a candidate root for this slot exists on disk. `Detected` means
 * "the slot exists", NOT "a usable version was extracted" — a `Detected`
 * record with empty `installations` (present but broken) is a
 * deliberately representable state.
 */
export type ClientPresenceStatus = "detected" | "notDetected";
