// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientKind } from "./ClientKind";

/**
 * One detected installation of a supported client. Each installation is
 * counted separately: a client installed twice (e.g. two Claude Code
 * installs) is reported as two `ClientInstallation` values, never merged.
 */
export type ClientInstallation = { client: ClientKind, version: string, path: string, };
