// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientInstallation } from "./ClientInstallation";
import type { ClientPresenceStatus } from "./ClientPresenceStatus";

/**
 * One probe slot's verdict. Exactly one record per slot the platform's
 * table defines (three on Windows), emitted whether or not anything
 * resolved. A slot is a *place we look*, not an installation: one record
 * MAY carry many installations (CA-7).
 */
export type ClientPresence = { 
/**
 * The slot's settled proper-noun label, e.g. "OpenCode (npm)".
 * Core-owned, unique within a report, never localized.
 */
label: string, 
/**
 * Every path probed for this slot, in deterministic order; the legacy
 * bundled path is always last. Non-empty by construction. Carried, not
 * displayed.
 */
probedPaths: Array<string>, status: ClientPresenceStatus, 
/**
 * Never `Option`, never reduced to "highest wins" (CA-7).
 */
installations: Array<ClientInstallation>, };
