// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One probe slot's identity, independent of and never inferred from
 * `ClientPresence.label`. Closed, exhaustively matchable — mirrors the
 * `Scope`/`ClientPresenceStatus` pattern. Growing this set follows
 * platform/adapter growth (T16), never speculative generality.
 */
export type ClientInstallSlot = "claudeCodeNpm" | "claudeCodeBundled" | "openCodeNpm" | "codexStandalone";
