// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed set of component kinds the PoC recognizes. No `#[non_exhaustive]`:
 * adding a variant is a breaking change that must be reviewed everywhere
 * this enum is matched.
 */
export type ComponentKind = "skill" | "agent";
