// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deterministic, human-readable identity for a `Component`: `"{kind
 * prefix}:{normalized name}"`. Stable across runs, processes, and
 * platforms — no RNG, no clock, no hashing.
 */
export type ComponentId = string;
