// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentId } from "./ComponentId";
import type { ComponentKind } from "./ComponentKind";
import type { Location } from "./Location";
import type { Scope } from "./Scope";

/**
 * One logical AI component (a skill, an agent, or an MCP server),
 * aggregated across every location it was found in. Discovering the same
 * component under N search roots yields ONE `Component` with N `Location`
 * entries sharing one `id`, never N separate components.
 */
export type Component = { id: ComponentId, 
/**
 * Raw display name, un-normalized. Identity is derived from a
 * normalized copy (`identity::normalize_name`); this field preserves
 * the original as the user or client would see it.
 */
name: string, kind: ComponentKind, description: string | null, scope: Scope, locations: Array<Location>, 
/**
 * Opaque display string describing provenance, absent when the adapter
 * has nothing to report. MUST NOT be branched on to drive behavior — any
 * machine-readable classification of a location's origin lives on
 * `Location::origin` instead. `Option` rather than an empty `String`:
 * "no hint" is a real state, not a sentinel value.
 */
provenanceHint: string | null, };
