// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The persisted opt-out/disclosure state for `component-freshness`,
 * crossing IPC so the frontend can render the opt-out switch and decide
 * whether to show the first-run disclosure. Distinct from
 * `FreshnessReport.enabled`: a report only ever exists after a check runs,
 * while a settings read must be possible before the first check has ever
 * happened. Not part of design's original §3 sketch — added when the
 * frontend slice closed the gap Slice 2 flagged (no command existed to
 * read or mutate `enabled`/`disclosure_seen`).
 */
export type FreshnessSettings = { enabled: boolean, disclosureSeen: boolean, };
