// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientInstallSlot } from "./ClientInstallSlot";

/**
 * The discriminator AND the id in one closed enum. Today one variant;
 * skills and agents arrive later as `Skill { id: ComponentId }` etc.
 * (`component-freshness` design §3).
 */
export type FreshnessSubject = { "clientInstallation": { slot: ClientInstallSlot, path: string, } };
