// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FreshnessCheck } from "./FreshnessCheck";

/**
 * The collection returned to the frontend. `enabled: false` means the user
 * turned the check off and NO request was issued — distinct from
 * every-check-`Unknown`, which means an attempt was made.
 */
export type FreshnessReport = { enabled: boolean, checks: Array<FreshnessCheck>, };
