// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Three-valued by settled decision (`component-freshness` design §7).
 * `Unknown` is a first-class outcome, not an error path. There is NO
 * fourth state: an installed version ahead of the latest reference is
 * `UpToDate`, never a separate "ahead"/"prerelease" variant.
 */
export type Freshness = "upToDate" | { "outdated": { latest: string, } } | { "unknown": { reason: string, } };
