// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { FreshnessSubject } from "./FreshnessSubject";

/**
 * One subject's installed version paired with its verdict. `installed` is
 * denormalised deliberately: the badge renders beside a version, and
 * without it the frontend would have to re-join on `path` across two
 * payloads returned at different times.
 */
export type FreshnessCheck = { subject: FreshnessSubject, installed: string, verdict: Freshness, };
