// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Two non-aborting severity levels. Severity is a display/triage signal
 * for later UI phases, not control flow.
 */
export type IssueSeverity = "warning" | "error";
