// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocationOrigin } from "./LocationOrigin";
import type { SearchRootId } from "./SearchRootId";

/**
 * One place a `Component` was found. `path` is optional: a component
 * reported without a backing file (`origin: Embedded`) is still
 * representable and stays distinguishable from a file-backed one.
 */
export type Location = { path: string | null, 
/**
 * Reference into `ScanReport::roots_scanned`, not an embedded
 * `SearchRoot` — the same root is never duplicated once per location.
 */
root: SearchRootId, origin: LocationOrigin, };
