// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientKind } from "./ClientKind";
import type { LocationOrigin } from "./LocationOrigin";
import type { McpTransport } from "./McpTransport";
import type { SearchRootId } from "./SearchRootId";

/**
 * One place a `Component` was found. `path` is optional: a component
 * reported without a backing file (`origin: Embedded`) is still
 * representable and stays distinguishable from a file-backed one.
 *
 * `Location` answers "where is this" for every kind, and, for MCP
 * locations only, also "how is it reached" via `mcp_transport`.
 */
export type Location = { path: string | null, 
/**
 * Reference into `ScanReport::roots_scanned`, not an embedded
 * `SearchRoot` — the same root is never duplicated once per location.
 */
root: SearchRootId, origin: LocationOrigin, 
/**
 * Connection detail, populated only for a `Location` produced by an
 * MCP adapter. `None` for a skill or agent location — always, and
 * unconditionally. For an MCP location, `None` means "configured
 * here, detail not safely capturable" (a degraded entry, paired with
 * a `Warning`), never "not an MCP location"; consumers MUST NOT infer
 * kind from this field.
 */
mcpTransport: McpTransport | null, 
/**
 * The owning client, copied from the `SearchRoot` that produced this
 * location. `None` means "shared root", never "unknown"; consumers
 * MUST NOT treat it as an error and MUST NOT infer component kind
 * from it.
 */
client: ClientKind | null, };
