// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Connection detail for one MCP `Location`. Closed, never
 * `#[non_exhaustive]`, and deliberately INCAPABLE of holding a secret:
 * there is no field for an `env` value, a `headers` value, or an
 * individual argument. Redaction is therefore a property of this type,
 * not a rule an adapter author can forget.
 */
export type McpTransport = { "stdio": { 
/**
 * The executable only. Never an argument, never an env value.
 */
command: string, 
/**
 * How many arguments were configured. A count cannot carry a value.
 */
arg_count: number, 
/**
 * Key NAMES from the environment map, in the map's own sorted
 * order. Never a value.
 */
env_keys: Array<string>, } } | { "remote": { 
/**
 * The sanitized ORIGIN of the configured endpoint —
 * `scheme://host[:port]`. Userinfo, query, fragment AND path are
 * removed before construction (design §3.2); this field is never
 * built from a raw configured string.
 */
url: string, 
/**
 * Key NAMES from the headers map. Never a value.
 */
header_keys: Array<string>, } };
