// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PromptError = { "invalidInput": { field: string, } } | { "notFound": { id: string, } } | { "storeUnavailable": { reason: string, } };
