// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Prompt = { id: string, title: string, body: string, tags: Array<string>, bestForContext: string | null, updatedAt: string, };
