// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Orchestration-level failure: the scan could not proceed at all.
 */
export type ScanError = { "kind": "noRootsConfigured" } | { "kind": "internal", "detail": { reason: string, } };
