// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientInstallation } from "./ClientInstallation";
import type { ClientPresence } from "./ClientPresence";
import type { Component } from "./Component";
import type { ScanIssue } from "./ScanIssue";
import type { SearchRoot } from "./SearchRoot";

/**
 * The complete result of one scan. Empty collections are a legitimate,
 * non-error value — `Err` is reserved for orchestration-level failure
 * where the scan could not run at all, never for "the scan ran and found
 * nothing".
 */
export type ScanReport = { components: Array<Component>, installations: Array<ClientInstallation>, rootsScanned: Array<SearchRoot>, issues: Array<ScanIssue>, 
/**
 * `None` means the current platform has no probe table at all (client
 * detection was not attempted). `Some(vec)` means the platform was
 * probed, with one [`ClientPresence`] per defined slot. `None` and
 * `Some(vec![])` are distinct and MUST NOT be used interchangeably.
 */
clientPresence: Array<ClientPresence> | null, 
/**
 * Value passed in by the caller, never measured here — this module
 * performs zero clock reads.
 */
durationMs: number, };
