// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientInstallation } from "./ClientInstallation";
import type { Component } from "./Component";
import type { ScanIssue } from "./ScanIssue";
import type { SearchRoot } from "./SearchRoot";

/**
 * The complete result of one scan. Empty collections are a legitimate,
 * non-error value — `Err` is reserved for orchestration-level failure
 * where the scan could not run at all, never for "the scan ran and found
 * nothing".
 */
export type ScanReport = { components: Array<Component>, installations: Array<ClientInstallation>, rootsScanned: Array<SearchRoot>, issues: Array<ScanIssue>, 
/**
 * Value passed in by the caller, never measured here — this module
 * performs zero clock reads.
 */
durationMs: number, };
