// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueSeverity } from "./IssueSeverity";

/**
 * One recoverable, per-item problem accumulated during a scan. Neither
 * severity level aborts the scan; every issue, of either severity, ends up
 * in `ScanReport::issues`.
 */
export type ScanIssue = { severity: IssueSeverity, 
/**
 * `None` when the issue has no meaningful file path (an absent root,
 * or an embedded component).
 */
path: string | null, reason: string, };
