// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed set of scopes a component can be discovered at. The PoC only ever
 * constructs `Scope::User`; `Project` and `Local` are modeled now so the
 * field never needs a breaking shape change later.
 */
export type Scope = "user" | "project" | "local";
