// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifier for a `SearchRoot`, used by `Location::root` to avoid
 * embedding (and duplicating) the full `SearchRoot` per location.
 */
export type SearchRootId = string;
