// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of component a `SearchRoot` is scanned for. Mirrors
 * `ComponentKind` because clients organize search roots per component kind
 * (e.g. a `skills/` directory and a separate `agents/` directory).
 */
export type SearchRootKind = "skill" | "agent";
