// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientKind } from "./ClientKind";
import type { SearchRootId } from "./SearchRootId";
import type { SearchRootKind } from "./SearchRootKind";
import type { SearchRootStatus } from "./SearchRootStatus";

/**
 * A directory the scanner walked to produce zero or more components. The
 * scanner is modeled as "one root produces N components", not "one client
 * has N components".
 */
export type SearchRoot = { id: SearchRootId, path: string, kind: SearchRootKind, status: SearchRootStatus, 
/**
 * The client that owns this search root. `None` for a shared root
 * with no single owner (`agents-skills`) — the same honest-`None`
 * pattern `Location.path` uses for embedded components. Ownership,
 * NOT the set of clients able to read the root.
 */
client: ClientKind | null, };
