// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchRootId } from "./SearchRootId";
import type { SearchRootKind } from "./SearchRootKind";

/**
 * A directory the scanner walked to produce zero or more components. The
 * scanner is modeled as "one root produces N components", not "one client
 * has N components".
 */
export type SearchRoot = { id: SearchRootId, path: string, kind: SearchRootKind, };
