// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a scan found this root's path on disk. Two-valued and
 * deliberately no wider: a root that exists but could not be read is
 * `Found` plus a `ScanIssue`, never a third status. `Found`/`NotFound`
 * rather than `Exists`/`Missing` because this is a statement about what one
 * scan observed, not a timeless fact about the path.
 */
export type SearchRootStatus = "found" | "notFound";
