// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BillingCycle } from "./BillingCycle";
import type { Currency } from "./Currency";

export type SubscriptionDraft = { provider: string, plan: string, amount: number, currency: Currency, cycle: BillingCycle, renewalDay: number, renewalMonth: number | null, };
