// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The single durable settings document's fields, crossing IPC.
 *
 * `locale` is free-form on purpose: core has no business knowing which
 * catalogs the frontend ships. An unrecognised value is treated as "no
 * explicit choice" by the frontend, which then falls through to
 * `navigator.languages`.
 */
export type UserSettings = { locale: string | null, enabled: boolean, disclosureSeen: boolean, };
